import { OverwritePattern } from './components/LetterOverwriteBox';

export interface PracticeTask {
  num: number;
  section: 'A' | 'B' | 'C' | 'D';
  kind: 'overwrite' | 'mcq' | 'fill';
  title: string;
  prompt: string;
  // For overwrite tasks (1-15)
  overwritePattern?: OverwritePattern;
  wordSuffix?: string;
  emoji?: string;
  themeIndex?: number;
  speakWord?: string;
  // For MCQ tasks (16-40)
  choices?: string[];
  answer?: number;
  // For Fill tasks (41-50)
  accepted?: string[];
  quickChips?: string[];
  hint: string;
}

export const tasks: PracticeTask[] = [
  // ============================================================================
  // SECTION A: 15 Interactive Overwriting & Tracing Box Tasks (Tasks 1–15)
  // ============================================================================
  {
    num: 1,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite Big Capital A',
    prompt: 'Trace over the partially visible Capital A in the box to fill it with complete 3D color! / बॉक्स में दिख रहे हल्के अक्षर A के ऊपर उंगली या माउस चलाकर पूरा रंग भरें!',
    overwritePattern: 'A',
    emoji: '🅰️',
    themeIndex: 0,
    speakWord: 'Capital A!',
    hint: 'Start at the top green dot: draw left slant (1), right slant (2), and middle sleeping bar (3). (ऊपर के बिंदु से बाईं रेखा, दाईं रेखा और बीच की आड़ी रेखा खींचें।)',
  },
  {
    num: 2,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite Stroke 1: Left Slanting Line (/)',
    prompt: 'Trace Stroke 1 from the top red line down to the left! / बिंदु 1 से नीचे बाईं ओर तिरछी रेखा (/) के ऊपर लिखें!',
    overwritePattern: 'stroke1',
    emoji: '1️⃣',
    themeIndex: 1,
    speakWord: 'Stroke one, slant down left!',
    hint: 'Stroke 1 starts at the top red line and slants down to the left blue line. (पहली रेखा ऊपर की लाल लाइन से बाईं ओर नीचे आती है।)',
  },
  {
    num: 3,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite Stroke 2: Right Slanting Line (\\)',
    prompt: 'Trace Stroke 2 from the top peak down to the right! / बिंदु 2 से नीचे दाईं ओर तिरछी रेखा (\\) के ऊपर लिखें!',
    overwritePattern: 'stroke2',
    emoji: '2️⃣',
    themeIndex: 2,
    speakWord: 'Stroke two, slant down right!',
    hint: 'Go back to the top peak and draw a slanting line down to the right. (वापस ऊपर के कोने से दाईं ओर नीचे तिरछी रेखा खींचें।)',
  },
  {
    num: 4,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite Stroke 3: Middle Sleeping Bridge (—)',
    prompt: 'Join both slanting lines by overwriting the middle sleeping line! / दोनों तिरछी रेखाओं को जोड़ने के लिए बीच की आड़ी रेखा (—) पर लिखें!',
    overwritePattern: 'stroke3',
    emoji: '3️⃣',
    themeIndex: 3,
    speakWord: 'Stroke three, sleeping line across! Capital A is complete!',
    hint: 'Draw a horizontal sleeping line across the middle blue line to connect the two sides of A. (बीच की नीली लाइन पर बाएं से दाएं आड़ी रेखा खींचकर A पूरा करें।)',
  },
  {
    num: 5,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite Small Letter a',
    prompt: 'Trace over the partially visible small letter "a" between the middle blue lines! / बीच की दो नीली लाइनों के अंदर छोटे अक्षर "a" के ऊपर लिखकर रंग भरें!',
    overwritePattern: 'a',
    emoji: '🔡',
    themeIndex: 4,
    speakWord: 'Small letter a!',
    hint: 'Curve around to make a round belly, then draw a short standing line down on the right. (पहले गोल घेरा बनाएं, फिर दाईं ओर छोटी खड़ी रेखा खींचें।)',
  },
  {
    num: 6,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite Capital A and Small a Together (Aa)',
    prompt: 'Trace both Capital A and small a in the box to light them up in 3D color! / बड़े अक्षर A और छोटे अक्षर a दोनों के ऊपर लिखकर रंग भरें!',
    overwritePattern: 'Aa',
    emoji: '✨',
    themeIndex: 0,
    speakWord: 'Capital A and small a!',
    hint: 'Capital A is tall (top 3 lines) and small a sits neatly inside the middle two blue lines. (बड़ा A ऊपर की 3 लाइनों में और छोटा a बीच की 2 नीली लाइनों में बनता है।)',
  },
  {
    num: 7,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite A for Apple (🍎)',
    prompt: 'Overwrite the partially visible A in the box to complete the word "Apple"! / "Apple" (सेब) शब्द पूरा करने के लिए हल्के अक्षर A के ऊपर लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'pple',
    emoji: '🍎',
    themeIndex: 0,
    speakWord: 'A for Apple!',
    hint: 'A is for Apple (सेब). Overwriting A completes the word Apple! (A से Apple यानी सेब बनता है।)',
  },
  {
    num: 8,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite A for Ant (🐜)',
    prompt: 'Overwrite the partially visible A in the box to complete the word "Ant"! / "Ant" (चींटी) शब्द पूरा करने के लिए अक्षर A के ऊपर लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'nt',
    emoji: '🐜',
    themeIndex: 1,
    speakWord: 'A for Ant!',
    hint: 'A is for Ant (चींटी). Trace the three strokes of A! (A से Ant यानी नन्हीं चींटी।)',
  },
  {
    num: 9,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite A for Aeroplane (✈️)',
    prompt: 'Overwrite the partially visible A in the box to complete "Aeroplane"! / "Aeroplane" (हवाई जहाज़) पूरा करने के लिए अक्षर A के ऊपर लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'eroplane',
    emoji: '✈️',
    themeIndex: 3,
    speakWord: 'A for Aeroplane!',
    hint: 'A is for Aeroplane (हवाई जहाज़) flying high in the sky! (A से Aeroplane यानी हवाई जहाज़।)',
  },
  {
    num: 10,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite A for Alligator (🐊)',
    prompt: 'Overwrite the partially visible A in the box to complete "Alligator"! / "Alligator" (मगरमच्छ) पूरा करने के लिए अक्षर A के ऊपर लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'lligator',
    emoji: '🐊',
    themeIndex: 1,
    speakWord: 'A for Alligator!',
    hint: 'A is for Alligator (मगरमच्छ). Trace the letter A to fill it with emerald green color! (A से Alligator यानी मगरमच्छ।)',
  },
  {
    num: 11,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite A for Astronaut (🧑‍🚀)',
    prompt: 'Overwrite the partially visible A in the box to complete "Astronaut"! / "Astronaut" (अंतरिक्ष यात्री) पूरा करने के लिए अक्षर A के ऊपर लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'stronaut',
    emoji: '🧑‍🚀',
    themeIndex: 4,
    speakWord: 'A for Astronaut!',
    hint: 'A is for Astronaut (अंतरिक्ष यात्री) who travels to space! (A से Astronaut यानी अंतरिक्ष यात्री।)',
  },
  {
    num: 12,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite A for Arrow (🏹)',
    prompt: 'Overwrite the partially visible A in the box to complete "Arrow"! / "Arrow" (तीर) पूरा करने के लिए अक्षर A के ऊपर लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'rrow',
    emoji: '🏹',
    themeIndex: 2,
    speakWord: 'A for Arrow!',
    hint: 'Notice how the top of Capital A looks just like the point of an Arrow (तीर)! (अक्षर A का ऊपरी कोना तीर की नोक जैसा दिखता है।)',
  },
  {
    num: 13,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite A for Axe (🪓)',
    prompt: 'Overwrite the partially visible A in the box to complete "Axe"! / "Axe" (कुल्हाड़ी) पूरा करने के लिए अक्षर A के ऊपर लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'xe',
    emoji: '🪓',
    themeIndex: 0,
    speakWord: 'A for Axe!',
    hint: 'A is for Axe (कुल्हाड़ी). Trace all 3 lines of Capital A! (A से Axe यानी कुल्हाड़ी।)',
  },
  {
    num: 14,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite A for Ambulance (🚑)',
    prompt: 'Overwrite the partially visible A in the box to complete "Ambulance"! / "Ambulance" (एम्बुलेंस) पूरा करने के लिए अक्षर A के ऊपर लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'mbulance',
    emoji: '🚑',
    themeIndex: 3,
    speakWord: 'A for Ambulance!',
    hint: 'A is for Ambulance (रोगी वाहन / एम्बुलेंस) that helps people! (A से Ambulance जो बीमार लोगों को अस्पताल पहुंचाती है।)',
  },
  {
    num: 15,
    section: 'A',
    kind: 'overwrite',
    title: 'Overwrite Trio: A · A · A Practice Row',
    prompt: 'Trace across all 3 partially visible A letters in the box to fill the entire row with 3D color! / बॉक्स में दिए गए तीनों हल्के A अक्षरों के ऊपर लिखकर पूरी पंक्ति में रंग भरें!',
    overwritePattern: 'A-trio',
    emoji: '🏆',
    themeIndex: 1,
    speakWord: 'A, A, A! Wonderful handwriting!',
    hint: 'Trace across all three Capital A letters from left to right to master steady handwriting! (तीनों A अक्षरों पर अभ्यास करने से बच्चे का हाथ सधता है।)',
  },

  // ============================================================================
  // SECTION B: Letter Recognition, Stroke Order & 4-Line Rules (Tasks 16–30)
  // ============================================================================
  {
    num: 16,
    section: 'B',
    kind: 'mcq',
    title: 'Which is the first letter of the English Alphabet?',
    prompt: 'Which letter comes first (Number 1) in the English Alphabet? / अंग्रेज़ी वर्णमाला (Alphabet) का सबसे पहला अक्षर कौन सा है?',
    choices: [
      'B (बी)',
      'A (ए)',
      'C (सी)',
      'D (डी)',
    ],
    answer: 1,
    hint: 'Letter A is the very first letter of the English alphabet! (अंग्रेज़ी वर्णमाला की शुरुआत अक्षर A से होती है।)',
  },
  {
    num: 17,
    section: 'B',
    kind: 'mcq',
    title: 'How many straight lines make Capital Letter A?',
    prompt: 'How many straight lines (strokes) do we draw to write Capital A? / बड़ा अक्षर A लिखने के लिए कुल कितनी सीधी रेखाएं खींची जाती हैं?',
    choices: [
      '1 line / केवल 1 रेखा',
      '2 lines / 2 रेखाएं',
      '3 lines (2 slanting + 1 sleeping) / 3 रेखाएं (2 तिरछी + 1 आड़ी)',
      '5 lines / 5 रेखाएं',
    ],
    answer: 2,
    hint: 'Capital A is made of 3 lines: Left slanting line (/), Right slanting line (\\), and Middle sleeping line (—). (बड़ा A कुल 3 रेखाओं से मिलकर बनता है।)',
  },
  {
    num: 18,
    section: 'B',
    kind: 'mcq',
    title: 'Where do we start writing Capital Letter A?',
    prompt: 'Where should your pencil start when writing Capital A? / बड़ा अक्षर A लिखते समय पेंसिल कहाँ से शुरू करनी चाहिए?',
    choices: [
      'At the top red line peak / सबसे ऊपर वाली लाल लाइन के बिंदु से',
      'At the bottom red line / सबसे नीचे वाली लाल लाइन से',
      'From the middle bridge / बीच की रेखा से',
      'Anywhere / कहीं से भी',
    ],
    answer: 0,
    hint: 'Always start Capital A at the top red line and slant down! (बड़ा अक्षर A हमेशा सबसे ऊपर वाली लाल लाइन के बिंदु से शुरू करके नीचे की ओर खींचा जाता है।)',
  },
  {
    num: 19,
    section: 'B',
    kind: 'mcq',
    title: 'Which stroke is drawn third (last) in Capital A?',
    prompt: 'What is the 3rd (last) stroke when writing Capital A? / बड़ा A लिखते समय तीसरी (आखिरी) रेखा कौन सी होती है?',
    choices: [
      'Left slanting line (/) / बाईं तिरछी रेखा',
      'Right slanting line (\\) / दाईं तिरछी रेखा',
      'Middle sleeping bridge line (—) / बीच में जोड़ने वाली आड़ी रेखा',
      'A big circle (O) / एक बड़ा गोला',
    ],
    answer: 2,
    hint: 'Stroke 3 is the sleeping line across the middle that joins the two slanting legs! (तीसरा कदम बीच में बाएं से दाएं आड़ी रेखा खींचना है।)',
  },
  {
    num: 20,
    section: 'B',
    kind: 'mcq',
    title: 'Spot the Small (Lowercase) Letter for A',
    prompt: 'Which of these is the small (lowercase) letter for Capital A? / बड़े अक्षर A का छोटा रूप (small letter) कौन सा है?',
    choices: [
      'b',
      'a',
      'o',
      'd',
    ],
    answer: 1,
    hint: '"a" is the lowercase partner of Capital "A". Together they are written as Aa. (बड़े A का छोटा अक्षर "a" होता है।)',
  },
  {
    num: 21,
    section: 'B',
    kind: 'mcq',
    title: '4-Line Notebook Rule for Capital A',
    prompt: 'In a 4-line English notebook, which lines does Capital A touch? / 4-लाइन वाली अंग्रेज़ी कॉपी में बड़ा अक्षर A किन लाइनों को छूता है?',
    choices: [
      'Top 3 lines (Top red line to second blue line) / ऊपर की 3 लाइनें (पहली लाल लाइन से दूसरी नीली लाइन तक)',
      'Only the bottom red line / केवल नीचे की लाल लाइन',
      'Only the middle 2 blue lines / केवल बीच की 2 नीली लाइनें',
      'All 4 lines / चारों लाइनें',
    ],
    answer: 0,
    hint: 'All capital letters, including Capital A, stand tall in the top 3 lines (Line 1 to Line 3). (बड़ा अक्षर A हमेशा ऊपर की तीन लाइनों में लिखा जाता है।)',
  },
  {
    num: 22,
    section: 'B',
    kind: 'mcq',
    title: '4-Line Notebook Rule for Small Letter a',
    prompt: 'In a 4-line notebook, where do we write small letter "a"? / 4-लाइन कॉपी में छोटा अक्षर "a" कहाँ लिखा जाता है?',
    choices: [
      'Inside the two middle blue lines / बीच की दो नीली लाइनों के अंदर',
      'Above the top red line / सबसे ऊपर की लाल लाइन के बाहर',
      'Touching the bottom red line / सबसे नीचे की लाल लाइन तक',
      'Across all 4 lines / चारों लाइनों में',
    ],
    answer: 0,
    hint: 'Small letter "a" sits snugly between the two middle blue lines (Line 2 and Line 3). (छोटा "a" बीच की दोनों नीली लाइनों के भीतर लिखा जाता है।)',
  },
  {
    num: 23,
    section: 'B',
    kind: 'mcq',
    title: 'Find Capital Letter A among Look-Alike Shapes',
    prompt: 'Look carefully! Which one is the correct Capital Letter A? / ध्यान से देखें! इनमें से सही बड़ा अक्षर A कौन सा है?',
    choices: [
      'V (उल्टा तिकोना बिना बीच की रेखा के)',
      'H (दो सीधी खड़ी रेखाएं)',
      'A (ऊपर से जुड़ा और बीच में आड़ी रेखा)',
      'M (चार रेखाओं वाला अक्षर)',
    ],
    answer: 2,
    hint: 'A has a pointed top like a roof and a bridge across the middle! (A ऊपर से तंबू या छत की तरह नुकीला होता है और बीच में पुल जैसी रेखा होती है।)',
  },
  {
    num: 24,
    section: 'B',
    kind: 'mcq',
    title: 'What happens if you forget Stroke 3 (the middle bar) of A?',
    prompt: 'If you draw the two slanting lines of A (/\\) but forget the middle sleeping line, what does it look like? / यदि आप A की दोनों तिरछी रेखाएं बनाएं पर बीच की आड़ी रेखा भूल जाएं, तो वह कैसा दिखेगा?',
    choices: [
      'An upside-down V (Λ) without a bridge / बिना पुल के उल्टे V जैसा',
      'A round circle O / गोल O जैसा',
      'The letter S / अक्षर S जैसा',
      'The number 8 / संख्या 8 जैसा',
    ],
    answer: 0,
    hint: 'Without the middle bar, A looks like an upside-down V (or a tent). Always add Stroke 3! (बीच की आड़ी रेखा के बिना A अधूरा रहता है।)',
  },
  {
    num: 25,
    section: 'B',
    kind: 'mcq',
    title: 'Match the Correct Capital + Small Pair',
    prompt: 'Which pair shows Capital A and small a together correctly? / कौन सा जोड़ा बड़ा A और छोटा a सही ढंग से दिखाता है?',
    choices: [
      'Ab',
      'Aa',
      'Ao',
      'Ad',
    ],
    answer: 1,
    hint: 'Capital A + small a = Aa! (सही जोड़ा Aa है।)',
  },
  {
    num: 26,
    section: 'B',
    kind: 'mcq',
    title: 'How many Letter As are in the word "BANANA"?',
    prompt: 'Count carefully! How many Capital A letters are in "B A N A N A"? / गिनकर बताएं! "B A N A N A" शब्द में कुल कितने A अक्षर हैं?',
    choices: [
      '1',
      '2',
      '3',
      '4',
    ],
    answer: 2,
    hint: 'B - A - N - A - N - A has three A letters! (इसमें कुल 3 बार A आया है।)',
  },
  {
    num: 27,
    section: 'B',
    kind: 'mcq',
    title: 'What shape does Capital Letter A look like?',
    prompt: 'Which real-life object looks most like the shape of Capital A? / बड़ा अक्षर A देखने में किस चीज़ के आकार जैसा लगता है?',
    choices: [
      'A pointed mountain tent or roof with a crossbar / तंबू या पहाड़ की चोटी जैसा',
      'A round football / गोल फुटबॉल जैसा',
      'A弯曲 snake / साँप जैसा',
      'A square box / चौकोर डिब्बे जैसा',
    ],
    answer: 0,
    hint: 'Capital A has a pointed peak at the top and two legs like a tent or ladder! (A का आकार तंबू या सीढ़ी जैसा होता है।)',
  },
  {
    num: 28,
    section: 'B',
    kind: 'mcq',
    title: 'How do we write Small Letter "a"?',
    prompt: 'What are the 2 steps to write small letter "a"? / छोटा अक्षर "a" लिखने के 2 आसान चरण क्या हैं?',
    choices: [
      '1. Make a small curve/circle left, 2. Draw a short standing line down on the right / पहले बाईं ओर छोटा गोला, फिर दाईं ओर छोटी खड़ी रेखा',
      'Draw three straight zig-zag lines / तीन टेढ़ी-मेढ़ी रेखाएं',
      'Draw two big circles / दो बड़े गोले',
      'Only one dot / केवल एक बिंदु',
    ],
    answer: 0,
    hint: 'Small "a" has a round belly on the left and a short standing tail on the right. (छोटा a बनाने के लिए पहले गोल पेट और फिर दाईं ओर छोटी खड़ी लकीर खींचते हैं।)',
  },
  {
    num: 29,
    section: 'B',
    kind: 'mcq',
    title: 'Good Pencil Grip for Overwriting Letters (Parent & Kid Tip)',
    prompt: 'How should a child hold the pencil while overwriting Letter A? / अक्षर A के ऊपर लिखते समय पेंसिल कैसे पकड़नी चाहिए?',
    choices: [
      'Gently with 3 fingers (Thumb, Index & Middle finger) / अंगूठे और दो उंगलियों से आराम से (Tripod Grip)',
      'With a tight fist / पूरी मुट्ठी बंद करके ज़ोर से',
      'With only the pinky finger / केवल सबसे छोटी उंगली से',
      'Upside down / उल्टा पकड़ कर',
    ],
    answer: 0,
    hint: 'Holding the pencil gently between thumb, pointer, and middle finger gives smooth control! (अंगूठे, तर्जनी और मध्यमा उंगली से पेंसिल पकड़ना सबसे सही तरीका है।)',
  },
  {
    num: 30,
    section: 'B',
    kind: 'mcq',
    title: 'Why do we overwrite on dotted/partially visible letters first?',
    prompt: 'Why does overwriting on partially visible letters help kids? / हल्के/बिंदु वाले अक्षरों के ऊपर लिखना (Overwriting) बच्चों के लिए क्यों उपयोगी है?',
    choices: [
      'It builds finger muscle memory and teaches exact letter shape / इससे हाथ सधता है और अक्षर की सही बनावट याद होती है',
      'It breaks the pencil / इससे पेंसिल टूटती है',
      'It hides the alphabet / इससे अक्षर छुप जाता है',
      'It has no use / इसका कोई लाभ नहीं है',
    ],
    answer: 0,
    hint: 'Overwriting guides the child’s hand along the right strokes until they can write independently! (अक्षर के ऊपर लिखकर रंग भरने से बच्चे का आत्मविश्वास और लेखन दोनों सुधरते हैं।)',
  },

  // ============================================================================
  // SECTION C: Phonics Sound & Words Starting with Letter A (Tasks 31–40)
  // ============================================================================
  {
    num: 31,
    section: 'C',
    kind: 'mcq',
    title: 'What short phonics sound does Letter A make?',
    prompt: 'What short sound does Letter A make in words like "Apple" and "Ant"? / "Apple" और "Ant" जैसे शब्दों में अक्षर A की ध्वनि (Phonics sound) क्या होती है?',
    choices: [
      '/æ/ — "ए / ऐ" (as in Apple / ऐप्पल)',
      '/m/ — "म" (as in Mango)',
      '/b/ — "ब" (as in Ball)',
      '/s/ — "स" (as in Sun)',
    ],
    answer: 0,
    hint: 'Letter A says /æ/ ("ऐ") as in Apple, Ant, Alligator, and Axe! (अक्षर A की मुख्य फोनेक्स ध्वनि "ऐ" या "ए" होती है।)',
  },
  {
    num: 32,
    section: 'C',
    kind: 'mcq',
    title: 'A is for 🍎 ________ (Sweet Red Fruit)',
    prompt: 'Which crunchy red fruit starts with Letter A? / कौन सा लाल और मीठा फल अक्षर A से शुरू होता है?',
    choices: [
      '🍎 Apple (सेब)',
      '🍌 Banana (केला)',
      '🥭 Mango (आम)',
      '🍇 Grapes (अंगूर)',
    ],
    answer: 0,
    hint: 'A for Apple! An apple is a healthy fruit that starts with A. (A से Apple यानी सेब होता है।)',
  },
  {
    num: 33,
    section: 'C',
    kind: 'mcq',
    title: 'A is for 🐜 ________ (Hardworking Tiny Insect)',
    prompt: 'Which tiny, hardworking insect starts with Letter A? / कौन सा नन्हा और मेहनती कीट अक्षर A से शुरू होता है?',
    choices: [
      '🐝 Bee (मधुमक्खी)',
      '🐜 Ant (चींटी)',
      '🦋 Butterfly (तितली)',
      '🕷️ Spider (मकड़ी)',
    ],
    answer: 1,
    hint: 'A for Ant (चींटी)! A-N-T spells Ant. (A से Ant यानी चींटी।)',
  },
  {
    num: 34,
    section: 'C',
    kind: 'mcq',
    title: 'A is for ✈️ ________ (Flies in the Sky)',
    prompt: 'What flies high in the clouds and starts with Letter A? / बादलों में ऊँचा उड़ने वाला कौन सा वाहन अक्षर A से शुरू होता है?',
    choices: [
      '🚂 Train (रेलगाड़ी)',
      '🚌 Bus (बस)',
      '✈️ Aeroplane (हवाई जहाज़)',
      '🚲 Bicycle (साइकिल)',
    ],
    answer: 2,
    hint: 'A for Aeroplane (हवाई जहाज़)! It begins with Letter A. (A से Aeroplane यानी हवाई जहाज़।)',
  },
  {
    num: 35,
    section: 'C',
    kind: 'mcq',
    title: 'A is for 🐊 ________ (Big Green River Animal)',
    prompt: 'Which big green reptile with sharp teeth starts with Letter A? / पानी और ज़मीन पर रहने वाला कौन सा बड़ा हरा जीव अक्षर A से शुरू होता है?',
    choices: [
      '🐊 Alligator (मगरमच्छ / घड़ियाल)',
      '🐘 Elephant (हाथी)',
      '🦁 Lion (शेर)',
      '🐒 Monkey (बंदर)',
    ],
    answer: 0,
    hint: 'A for Alligator (मगरमच्छ)! It starts with A. (A से Alligator यानी मगरमच्छ।)',
  },
  {
    num: 36,
    section: 'C',
    kind: 'mcq',
    title: 'A is for 🪓 ________ (Woodcutter’s Tool)',
    prompt: 'Which tool used to chop wood starts with Letter A? / लकड़ी काटने के काम आने वाला कौन सा औज़ार अक्षर A से शुरू होता है?',
    choices: [
      '🔨 Hammer (हथौड़ा)',
      '🪓 Axe (कुल्हाड़ी)',
      '🥄 Spoon (चम्मच)',
      '🔑 Key (चाबी)',
    ],
    answer: 1,
    hint: 'A for Axe (कुल्हाड़ी)! A-X-E spells Axe. (A से Axe यानी कुल्हाड़ी।)',
  },
  {
    num: 37,
    section: 'C',
    kind: 'mcq',
    title: 'A is for 🚑 ________ (Hospital Emergency Vehicle)',
    prompt: 'Which emergency van with a siren starts with Letter A? / सायरन बजाते हुए मरीज़ों को अस्पताल ले जाने वाली गाड़ी का नाम किस अक्षर से शुरू होता है?',
    choices: [
      '🚑 Ambulance (एम्बुलेंस)',
      '🚜 Tractor (ट्रैक्टर)',
      '⛵ Boat (नाव)',
      '🛴 Scooter (स्कूटर)',
    ],
    answer: 0,
    hint: 'A for Ambulance (एम्बुलेंस)! Notice that AMBULANCE starts with Capital A. (A से Ambulance होती है।)',
  },
  {
    num: 38,
    section: 'C',
    kind: 'mcq',
    title: 'A is for 🧑‍🚀 ________ (Space Explorer)',
    prompt: 'Who wears a spacesuit, travels in a rocket, and starts with Letter A? / अंतरिक्ष में जाने वाले यात्री को अंग्रेज़ी में क्या कहते हैं जो A से शुरू होता है?',
    choices: [
      '🧑‍🚀 Astronaut (अंतरिक्ष यात्री)',
      '👨‍🌾 Farmer (किसान)',
      '👨‍🍳 Chef (रसोइया)',
      '👮 Police (पुलिस)',
    ],
    answer: 0,
    hint: 'A for Astronaut (अंतरिक्ष यात्री)! (A से Astronaut यानी अंतरिक्ष यात्री।)',
  },
  {
    num: 39,
    section: 'C',
    kind: 'mcq',
    title: 'A is for 🏹 ________ (Pointed Direction Sign)',
    prompt: 'What pointed symbol shows direction and starts with Letter A? / दिशा दिखाने वाले नुकीले तीर को अंग्रेज़ी में क्या कहते हैं जो A से शुरू होता है?',
    choices: [
      '🏹 Arrow (तीर)',
      '⭐ Star (तारा)',
      '🔔 Bell (घंटी)',
      '🎈 Balloon (गुब्बारा)',
    ],
    answer: 0,
    hint: 'A for Arrow (तीर)! A-R-R-O-W starts with A. (A से Arrow यानी तीर।)',
  },
  {
    num: 40,
    section: 'C',
    kind: 'mcq',
    title: 'A is for ⚓ ________ (Holds a Ship in Place)',
    prompt: 'What heavy metal hook holds a ship steady in water and starts with Letter A? / पानी के जहाज़ को एक जगह रोकने वाले भारी लोहे के लंगर को क्या कहते हैं?',
    choices: [
      '⚓ Anchor (लंगर)',
      '☂️ Umbrella (छाता)',
      '🪁 Kite (पतंग)',
      '🥁 Drum (ढोल)',
    ],
    answer: 0,
    hint: 'A for Anchor (लंगर)! It starts with Letter A. (A से Anchor यानी जहाज़ का लंगर।)',
  },

  // ============================================================================
  // SECTION D: Write & Complete Letter A Words (Tasks 41–50)
  // ============================================================================
  {
    num: 41,
    section: 'D',
    kind: 'fill',
    title: 'Type or Tap Capital Letter A',
    prompt: 'Write the first letter of the alphabet: ________ / वर्णमाला का पहला अक्षर लिखें (या नीचे बटन दबाएं):',
    accepted: ['a'],
    quickChips: ['A', 'B', 'C'],
    hint: 'Type or tap "A" — the very first letter of the alphabet! (अक्षर A टाइप करें या चुनें।)',
  },
  {
    num: 42,
    section: 'D',
    kind: 'fill',
    title: 'Type or Tap Capital & Small Pair (Aa)',
    prompt: 'Write Capital A and small a together: ________ / बड़ा A और छोटा a एक साथ लिखें (Aa):',
    accepted: ['aa', 'a a'],
    quickChips: ['Aa', 'Bb', 'Cc'],
    hint: 'Together, Capital A and lowercase a are written as "Aa". (दोनों को मिलाकर Aa लिखते हैं।)',
  },
  {
    num: 43,
    section: 'D',
    kind: 'fill',
    title: 'Complete the Word: 🍎 _pple',
    prompt: 'Fill in the missing letter A to complete: 🍎 ________pple (or write full word Apple) / सेब की स्पेलिंग पूरी करें:',
    accepted: ['a', 'apple'],
    quickChips: ['A', 'Apple', 'Ball'],
    hint: 'Put "A" at the start to make "Apple" (सेब)! (शुरू में A लगाने से Apple बनता है।)',
  },
  {
    num: 44,
    section: 'D',
    kind: 'fill',
    title: 'Complete the Word: 🐜 _nt',
    prompt: 'Fill in the missing letter A to complete: 🐜 ________nt (or write Ant) / चींटी की स्पेलिंग पूरी करें:',
    accepted: ['a', 'ant'],
    quickChips: ['A', 'Ant', 'Cat'],
    hint: 'Put "A" at the beginning to make "Ant" (चींटी)! (A-N-T = Ant यानी चींटी।)',
  },
  {
    num: 45,
    section: 'D',
    kind: 'fill',
    title: 'Complete the Word: 🪓 _xe',
    prompt: 'Fill in the missing letter A to complete: 🪓 ________xe (or write Axe) / कुल्हाड़ी की स्पेलिंग पूरी करें:',
    accepted: ['a', 'axe'],
    quickChips: ['A', 'Axe', 'Box'],
    hint: 'Put "A" at the beginning to make "Axe" (कुल्हाड़ी)! (A-X-E = Axe यानी कुल्हाड़ी।)',
  },
  {
    num: 46,
    section: 'D',
    kind: 'fill',
    title: 'Complete the Body Part Word: 💪 _rm',
    prompt: 'Our shoulder to hand is called an 💪 ________rm. Fill in Letter A (or write Arm)! / हमारी बांह को अंग्रेज़ी में क्या कहते हैं? अक्षर A भरें:',
    accepted: ['a', 'arm'],
    quickChips: ['A', 'Arm', 'Leg'],
    hint: 'A-R-M spells Arm (बांह / भुजा)! (A लगाने से Arm यानी बांह बनता है।)',
  },
  {
    num: 47,
    section: 'D',
    kind: 'fill',
    title: 'Complete the Creative Word: 🎨 _rt',
    prompt: 'Drawing and coloring is called 🎨 ________rt. Fill in Letter A (or write Art)! / चित्रकला और रंग भरने को अंग्रेज़ी में क्या कहते हैं?',
    accepted: ['a', 'art'],
    quickChips: ['A', 'Art', 'Sun'],
    hint: 'A-R-T spells Art (कला / चित्रकला)! (A लगाने से Art यानी कला बनता है।)',
  },
  {
    num: 48,
    section: 'D',
    kind: 'fill',
    title: 'Complete the Direction Word: 🏹 _rrow',
    prompt: 'Fill in Letter A to complete: 🏹 ________rrow (or write Arrow) / तीर की स्पेलिंग पूरी करें:',
    accepted: ['a', 'arrow'],
    quickChips: ['A', 'Arrow', 'Bow'],
    hint: 'A-R-R-O-W spells Arrow (तीर)! (शुरू में A लगाने से Arrow बनता है।)',
  },
  {
    num: 49,
    section: 'D',
    kind: 'fill',
    title: 'Fill Small "a" in the Middle: 🐱 c _ t',
    prompt: 'Put small letter "a" in the middle of c ___ t (or write cat) / बिल्ली (cat) शब्द के बीच में छोटा अक्षर "a" भरें:',
    accepted: ['a', 'cat'],
    quickChips: ['a', 'cat', 'dog'],
    hint: 'c + a + t = cat (बिल्ली)! Small letter "a" gives the /æ/ sound in the middle of cat. (बीच में छोटा a लिखने से cat बनता है।)',
  },
  {
    num: 50,
    section: 'D',
    kind: 'fill',
    title: 'Fill Small "a" in the Middle: 🏏 b _ t',
    prompt: 'Put small letter "a" in the middle of b ___ t (or write bat) / बल्ला (bat) शब्द के बीच में छोटा अक्षर "a" भरें:',
    accepted: ['a', 'bat'],
    quickChips: ['a', 'bat', 'ball'],
    hint: 'b + a + t = bat (बल्ला)! You finished all 50 tasks for Letter A! (बीच में a लिखने से bat बनता है। बधाई हो, पूरे 50 अभ्यास पूरे हुए!)',
  },
];
