import { OverwritePattern } from './components/LetterOverwriteBox';

export interface PracticeTask {
  num: number;
  title: string;
  prompt: string;
  overwritePattern: OverwritePattern;
  wordSuffix?: string;
  emoji: string;
  objectName: string;
  objectNameHi: string;
  objectDescHi: string;
  themeIndex: number;
  speakWord: string;
  hint: string;
}

export const tasks: PracticeTask[] = [
  {
    num: 1,
    title: 'Task 1 · Overwrite Capital A (A for Apple)',
    prompt: 'Trace over the Capital Letter A in the box to fill it with 3D color! / बॉक्स में अक्षर A के ऊपर उंगली या माउस चलाकर रंग भरें!',
    overwritePattern: 'A',
    wordSuffix: 'pple',
    emoji: '🍎',
    objectName: 'Apple',
    objectNameHi: 'सेब (ऐप्पल)',
    objectDescHi: 'A for Apple — मीठा लाल सेब',
    themeIndex: 0,
    speakWord: 'A for Apple!',
    hint: 'Start at the top dot: draw left slant (1), right slant (2), and middle bar (3). (ऊपर से दोनों तिरछी रेखाएं और बीच की रेखा खींचें।)',
  },
  {
    num: 2,
    title: 'Task 2 · Overwrite Left Slant Line (/) — A for Ant',
    prompt: 'Trace Stroke 1 from the top red line down to the left! / बिंदु 1 से नीचे बाईं ओर तिरछी रेखा (/) के ऊपर लिखें!',
    overwritePattern: 'stroke1',
    emoji: '🐜',
    objectName: 'Ant',
    objectNameHi: 'चींटी (ऐन्ट)',
    objectDescHi: 'A for Ant — नन्हीं मेहनती चींटी',
    themeIndex: 1,
    speakWord: 'A for Ant! Stroke one, slant down left!',
    hint: 'Stroke 1 starts at the top red line and slants down to the left blue line. (पहली रेखा ऊपर से बाईं ओर नीचे आती है।)',
  },
  {
    num: 3,
    title: 'Task 3 · Overwrite Right Slant Line (\\) — A for Aeroplane',
    prompt: 'Trace Stroke 2 from the top peak down to the right! / बिंदु 2 से नीचे दाईं ओर तिरछी रेखा (\\) के ऊपर लिखें!',
    overwritePattern: 'stroke2',
    emoji: '✈️',
    objectName: 'Aeroplane',
    objectNameHi: 'हवाई जहाज़ (एरोप्लेन)',
    objectDescHi: 'A for Aeroplane — आसमान में उड़ने वाला हवाई जहाज़',
    themeIndex: 3,
    speakWord: 'A for Aeroplane! Stroke two, slant down right!',
    hint: 'Go to the top peak and draw a slanting line down to the right. (ऊपर के कोने से दाईं ओर नीचे तिरछी रेखा खींचें।)',
  },
  {
    num: 4,
    title: 'Task 4 · Overwrite Middle Line (—) — A for Arrow',
    prompt: 'Trace the middle sleeping line across! / बीच की आड़ी रेखा (—) के ऊपर लिखें!',
    overwritePattern: 'stroke3',
    emoji: '🏹',
    objectName: 'Arrow',
    objectNameHi: 'तीर (ऐरो)',
    objectDescHi: 'A for Arrow — निशाना लगाने वाला तीर',
    themeIndex: 2,
    speakWord: 'A for Arrow! Sleeping line across!',
    hint: 'Draw a sleeping line across the middle blue line. (बीच की नीली लाइन पर बाएं से दाएं आड़ी रेखा खींचें।)',
  },
  {
    num: 5,
    title: 'Task 5 · Overwrite Small Letter a — a for Alligator',
    prompt: 'Trace over the small letter "a" between the middle blue lines! / छोटे अक्षर "a" के ऊपर लिखकर रंग भरें!',
    overwritePattern: 'a',
    emoji: '🐊',
    objectName: 'Alligator',
    objectNameHi: 'मगरमच्छ (ऐलिगेटर)',
    objectDescHi: 'A for Alligator — पानी में रहने वाला मगरमच्छ',
    themeIndex: 1,
    speakWord: 'Small letter a! A for Alligator!',
    hint: 'Make a round belly curve first, then draw a short standing line down on the right. (पहले गोल घेरा बनाएं, फिर दाईं ओर छोटी खड़ी रेखा खींचें।)',
  },
  {
    num: 6,
    title: 'Task 6 · Overwrite Both Aa — A for Astronaut',
    prompt: 'Trace both Capital A and small a in the box! / बड़े A और छोटे a दोनों के ऊपर लिखकर रंग भरें!',
    overwritePattern: 'Aa',
    emoji: '🧑‍🚀',
    objectName: 'Astronaut',
    objectNameHi: 'अंतरिक्ष यात्री (ऐस्ट्रोनॉट)',
    objectDescHi: 'A for Astronaut — अंतरिक्ष में जाने वाला यात्री',
    themeIndex: 4,
    speakWord: 'Capital A and small a! A for Astronaut!',
    hint: 'Trace tall Capital A first, then trace small a right beside it. (पहले बड़ा A और फिर छोटा a ट्रेस करें।)',
  },
  {
    num: 7,
    title: 'Task 7 · Overwrite A for Ambulance',
    prompt: 'Overwrite Capital A to complete the word "Ambulance"! / "Ambulance" (एम्बुलेंस) का पहला अक्षर A लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'mbulance',
    emoji: '🚑',
    objectName: 'Ambulance',
    objectNameHi: 'एम्बुलेंस (अस्पताल की गाड़ी)',
    objectDescHi: 'A for Ambulance — बीमार लोगों की मदद करने वाली गाड़ी',
    themeIndex: 0,
    speakWord: 'A for Ambulance!',
    hint: 'Trace all 3 strokes of Capital A to complete Ambulance. (A की तीनों रेखाओं पर उंगली चलाएं।)',
  },
  {
    num: 8,
    title: 'Task 8 · Overwrite A for Axe',
    prompt: 'Overwrite Capital A to complete the word "Axe"! / "Axe" (कुल्हाड़ी) शब्द पूरा करने के लिए A के ऊपर लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'xe',
    emoji: '🪓',
    objectName: 'Axe',
    objectNameHi: 'कुल्हाड़ी (ऐक्स)',
    objectDescHi: 'A for Axe — लकड़ी काटने वाली कुल्हाड़ी',
    themeIndex: 2,
    speakWord: 'A for Axe!',
    hint: 'A - X - E spells Axe! Trace Capital A completely. (A से Axe यानी कुल्हाड़ी।)',
  },
  {
    num: 9,
    title: 'Task 9 · Overwrite A for Anchor',
    prompt: 'Overwrite Capital A to complete the word "Anchor"! / "Anchor" (लंगर) शब्द पूरा करने के लिए A के ऊपर लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'nchor',
    emoji: '⚓',
    objectName: 'Anchor',
    objectNameHi: 'लंगर (ऐंकर)',
    objectDescHi: 'A for Anchor — पानी के बड़े जहाज़ को रोकने वाला लंगर',
    themeIndex: 3,
    speakWord: 'A for Anchor!',
    hint: 'A is for Anchor! Trace the two slanting lines and middle bar. (A से Anchor यानी जहाज़ का लंगर।)',
  },
  {
    num: 10,
    title: 'Task 10 · Overwrite A for Aquarium',
    prompt: 'Overwrite Capital A to complete the word "Aquarium"! / "Aquarium" (मछलीघर) पूरा करने के लिए अक्षर A लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'quarium',
    emoji: '🐠',
    objectName: 'Aquarium',
    objectNameHi: 'मछलीघर (अक्वेरियम)',
    objectDescHi: 'A for Aquarium — रंग-बिरंगी मछलियों का घर',
    themeIndex: 1,
    speakWord: 'A for Aquarium!',
    hint: 'A is for Aquarium! Overwrite Capital A to light it up in 3D color. (A से Aquarium यानी मछलीघर।)',
  },
  {
    num: 11,
    title: 'Task 11 · Overwrite A for Alarm Clock',
    prompt: 'Overwrite Capital A to complete the word "Alarm"! / "Alarm" (अलार्म घड़ी) पूरा करने के लिए A के ऊपर लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'larm',
    emoji: '⏰',
    objectName: 'Alarm Clock',
    objectNameHi: 'अलार्म घड़ी (अलार्म क्लॉक)',
    objectDescHi: 'A for Alarm Clock — सुबह जगाने वाली घड़ी',
    themeIndex: 0,
    speakWord: 'A for Alarm Clock!',
    hint: 'A is for Alarm Clock that wakes us up in the morning! (A से Alarm Clock जो सुबह जगाती है।)',
  },
  {
    num: 12,
    title: 'Task 12 · Overwrite A for Avocado',
    prompt: 'Overwrite Capital A to complete the word "Avocado"! / "Avocado" (एवोकाडो फल) पूरा करने के लिए A के ऊपर लिखें!',
    overwritePattern: 'A',
    wordSuffix: 'vocado',
    emoji: '🥑',
    objectName: 'Avocado',
    objectNameHi: 'एवोकाडो (हरा फल)',
    objectDescHi: 'A for Avocado — सेहतमंद हरा फल',
    themeIndex: 1,
    speakWord: 'A for Avocado!',
    hint: 'A is for healthy green Avocado! Trace all three lines of A. (A से Avocado फल।)',
  },
  {
    num: 13,
    title: 'Task 13 · Overwrite Small a — a for Acorn',
    prompt: 'Trace over the small letter "a" in the box! / बॉक्स में छोटे अक्षर "a" के ऊपर हाथ फेरकर रंग भरें!',
    overwritePattern: 'a',
    emoji: '🌰',
    objectName: 'Acorn',
    objectNameHi: 'बलूत का फल (एकॉर्न)',
    objectDescHi: 'A for Acorn — गिलहरी का पसंदीदा फल',
    themeIndex: 2,
    speakWord: 'A for Acorn! Small letter a!',
    hint: 'Curve around in the middle blue lines and draw a short standing line down. (बीच की दो नीली लाइनों में छोटा a बनाएं।)',
  },
  {
    num: 14,
    title: 'Task 14 · Overwrite Capital & Small Aa — A for Art',
    prompt: 'Trace both Capital A and small a in the box! / बड़े A और छोटे a दोनों के ऊपर लिखें!',
    overwritePattern: 'Aa',
    emoji: '🎨',
    objectName: 'Art',
    objectNameHi: 'चित्रकला (आर्ट)',
    objectDescHi: 'A for Art — रंगों से चित्र बनाना',
    themeIndex: 4,
    speakWord: 'A for Art! Capital A and small a!',
    hint: 'Overwrite both Capital A and small a to fill them with bright colors! (दोनों अक्षरों पर हाथ फेरकर रंग भरें।)',
  },
  {
    num: 15,
    title: 'Task 15 · Overwrite A · A · A Champion Row',
    prompt: 'Trace across all 3 Capital A letters in the box! / बॉक्स में दिए गए तीनों बड़े A अक्षरों के ऊपर लिखें!',
    overwritePattern: 'A-trio',
    emoji: '🏆',
    objectName: 'Apple · Ant · Aeroplane',
    objectNameHi: 'सेब · चींटी · हवाई जहाज़',
    objectDescHi: 'A · A · A — तीनों A लिखकर चैंपियन बनें!',
    themeIndex: 0,
    speakWord: 'A, A, A! Champion!',
    hint: 'Trace all three Capital A letters from left to right! (बाएं से दाएं तीनों A अक्षरों के ऊपर लिखें।)',
  },
];
